import { Color } from 'antd/es/color-picker';
export type SettingsPropsType = {
  chatbotIdP?: string;
  charCountP?: number;
  nameP?: string;
  basePromptP?: string;
  modelP?: string;
  temperatureP?: number;
  visibilityP?: string;
  domainsP?: string;
  messageLimitP?: number;
  messagePeriodP?: number;
  limitHitMessageP?: string;
  showTitleCustomerP?: boolean;
  titleCustomerP?: string;
  showNameCustomerP?: boolean;
  nameCustomerP?: string;
  showEmailCustomerP?: boolean;
  emailCustomerP?: string;
  showPhoneCustomerP?: boolean;
  phoneNumberCustomerP?: string;
  initialMessagesP?: string;
  suggestedMessagesP?: string;
  themeP?: string;
  profilePictureP?: string;
  removeProfilePictureP?: boolean;
  userMessageColorP?: string | Color;
  chatFooterColorP?: string | Color;
  chatMessageColorP?: string | Color;
};
